# Generated by Django 2.2.4 on 2019-08-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190806_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='zicode',
            new_name='zipcode',
        ),
    ]
